window.services = {
	REPORTING: REPORTING,
	PAYMENT: PAYMENT,
	A_B_TESTING: A_B_TESTING,
	CLICK_TRACING: CLICK_TRACING,
	EXPERMENTAL_FEATURE_1: EXPERMENTAL_FEATURE_1,
	EXPERMENTAL_FEATURE_2: EXPERMENTAL_FEATURE_2
};
